name: Scheduled Web Scraper

on:
  schedule:
    - cron: '30 15 * * *'   # Jam 15:30 UTC / 22:30 UTC+7
    - cron: '30 3 * * *'    # Jam 03:30 UTC / 10:30 UTC+7
  workflow_dispatch:        # Bisa dijalankan manual juga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install puppeteer

      - name: Jalankan scraper
        run: node scrape.js

      - name: Commit dan push hasil scraping
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/data.json
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push origin HEAD:main
